version: '3.6'

services:
  message-board:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-3000}/api/message || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s